### ISSUE TITLE
Add configuration system

### ISSUE THREAD

**Issue by Draylar** [Brandcraf06/NetherThings#8]
Would be great if you added a config to enable & disable certain features. [Auto Config](https://gitlab.com/sargunv-mc-mods/auto-config/wikis/home) would make it fairly easy, and [LibCD](https://github.com/CottonMC/LibCD) could be used to conditionally load recipes to prevent log spam.

Config options:
 - nether mushroom generation
 - nether cactus generation
 - overworld nether-ores
 - nether overworld-ores
 - armor/tool stats
 - ore rarity

Are you interested in doing this? If not, I can implement it and send in a PR.

Thanks!

**Comment by Brandcraf06** [comment]
I'm trying to find out how to make one for a while, without success. And I didn't know Auto Config.

I'm not against help in a PR to see a little how it's going. Especially, for new features or for my other mods. If it doesn't mind ?

Thanks to you
